blank_issues_enabled: false
templates:
  - name: 機能リクエスト
    description: 新機能の提案テンプレート
    file: feature_request.yml

  - name: ドキュメント関連
    description: ドキュメントに関する変更・修正などのテンプレート
    file: document.yml

  - name: 質問
    description: 質問に関するテンプレート
    file: question.yml
