name: 機能開発
description: 新機能・修正・変更はこちらから
title: "[機能開発] "
labels: ["新機能リクエスト"]
body:
  - type: input
    id: overview
    attributes:
      label: 概要
      description: 簡単に提案の内容を記述してください
      placeholder: ユーザー管理機能の追加

  - type: textarea
    id: objective
    attributes:
      label: 目的
      description: なぜこの機能が必要なのか、背景を説明してください
      placeholder: 操作性や機能性の向上など

  - type: textarea
    id: implementation
    attributes:
      label: 実装内容
      description: 具体的な実装案や作業項目（チェックボックスもOK）
      value: |
        - [ ] 画面レイアウトの改修
        - [ ] APIの新設
        - [ ] ドキュメント更新

  - type: textarea
    id: notes
    attributes:
      label: 備考
      description: 関連Issueや参考情報があれば記述してください
